#!/bin/sh
# SPDX-License-Identifier: GPL-2.0+
#
# Probe the target kernel's external-module build environment for the DRM
# atomic aggregate rename. This intentionally dereferences the type: a mere
# forward declaration must not count as support.

set -eu

kdir=
output=

while test "$#" -gt 0; do
	case "$1" in
	--kdir)
		test "$#" -ge 2 || { echo "missing value for --kdir" >&2; exit 2; }
		kdir=$2
		shift 2
		;;
	--output)
		test "$#" -ge 2 || { echo "missing value for --output" >&2; exit 2; }
		output=$2
		shift 2
		;;
	*)
		echo "unknown argument: $1" >&2
		exit 2
		;;
	esac
done

test -n "$kdir" || { echo "--kdir is required" >&2; exit 2; }
test -n "$output" || { echo "--output is required" >&2; exit 2; }
test -d "$kdir" || { echo "kernel build tree is missing: $kdir" >&2; exit 2; }
test -f "$kdir/Makefile" || { echo "kernel build Makefile is missing: $kdir/Makefile" >&2; exit 2; }
test -d "$(dirname "$output")" || { echo "feature-header directory is missing: $(dirname "$output")" >&2; exit 2; }

probe_dir=$(mktemp -d "${TMPDIR:-/tmp}/monitorize-vkms-atomic-probe.XXXXXX")
trap 'rm -rf "$probe_dir"' EXIT HUP INT TERM
probe_log="$probe_dir/build.log"
feature_tmp="$probe_dir/vkms_oot_features.h"

printf '%s\n' 'obj-m := probe.o' > "$probe_dir/Makefile"
printf '%s\n' \
	'#include <linux/module.h>' \
	'#include <drm/drm_atomic.h>' \
	'' \
	'static void __maybe_unused vkms_oot_probe_type(struct drm_atomic_commit *commit)' \
	'{' \
	'	(void)commit->dev;' \
	'}' \
	'' \
	'MODULE_LICENSE("GPL");' > "$probe_dir/probe.c"

if make -C "$kdir" M="$probe_dir" modules > "$probe_log" 2>&1; then
	has_drm_atomic_commit=1
elif grep -Eq 'probe\.c:.*(invalid use of undefined type|undefined type).*drm_atomic_commit' "$probe_log"; then
	has_drm_atomic_commit=0
else
	echo "DRM atomic API probe failed for reasons other than an absent drm_atomic_commit type:" >&2
	cat "$probe_log" >&2
	exit 1
fi

printf '%s\n' \
	'/* SPDX-License-Identifier: GPL-2.0+ */' \
	'/* Generated by the monitorize-vkms build; do not edit manually. */' \
	'#ifndef _VKMS_OOT_FEATURES_H_' \
	'#define _VKMS_OOT_FEATURES_H_' \
	'' \
	"#define VKMS_OOT_HAS_DRM_ATOMIC_COMMIT $has_drm_atomic_commit" \
	'' \
	'#endif /* _VKMS_OOT_FEATURES_H_ */' > "$feature_tmp"

if test ! -f "$output" || ! cmp -s "$feature_tmp" "$output"; then
	mv "$feature_tmp" "$output"
fi
